import {
    CircleAlert,
    TriangleAlert,
    Square,
    User,
    Tag,
    ChevronRight,
    MousePointer2,
    Calendar,
    CreditCard,
    Images,
    SquareCheck,
    ChevronsUpDown,
    Command,
    MousePointerClick,
    MessageSquare,
    PanelBottom,
    Menu,
    LayoutGrid,
    Type,
    Hash,
    CaseSensitive,
    Columns2,
    Compass,
    Ellipsis,
    MessageCircle,
    LoaderCircle,
    Circle,
    GripVertical,
    Scroll,
    ListFilter,
    Minus,
    PanelRight,
    Ghost,
    SlidersHorizontal,
    Bell,
    ToggleLeft,
    Table,
    Folder,
    FileText,
    Power,
    Grid3x3,
    Info,
    Box,
} from 'lucide-react-taro'

export const iconMap: Record<string, any> = {
    Button: MousePointer2,
    Badge: Tag,
    Avatar: User,
    Separator: Minus,
    AspectRatio: Square,
    Card: CreditCard,
    Resizable: GripVertical,
    ScrollArea: Scroll,
    Checkbox: SquareCheck,
    Field: LayoutGrid,
    Input: Type,
    InputOTP: Hash,
    Label: CaseSensitive,
    RadioGroup: Circle,
    Select: ListFilter,
    Slider: SlidersHorizontal,
    Switch: ToggleLeft,
    Textarea: FileText,
    Toggle: Power,
    ToggleGroup: Grid3x3,
    Accordion: ChevronsUpDown,
    Calendar: Calendar,
    Carousel: Images,
    Table: Table,
    Alert: CircleAlert,
    Progress: LoaderCircle,
    Skeleton: Ghost,
    Sonner: Bell,
    Toast: MessageSquare,
    Breadcrumb: ChevronRight,
    Command: Command,
    Menubar: Columns2,
    NavigationMenu: Compass,
    Pagination: Ellipsis,
    Tabs: Folder,
    AlertDialog: TriangleAlert,
    ContextMenu: MousePointerClick,
    Dialog: MessageSquare,
    Drawer: PanelBottom,
    DropdownMenu: Menu,
    HoverCard: MousePointer2,
    Popover: MessageCircle,
    Sheet: PanelRight,
    Tooltip: Info,
    Collapsible: ChevronsUpDown,
}

export const getIcon = (name: string) => {
    return iconMap[name] || Box
}

export const components = [
    { name: 'Accordion', path: '/pages/ui/accordion/index' },
    { name: 'Alert', path: '/pages/ui/alert/index' },
    { name: 'AlertDialog', path: '/pages/ui/alert-dialog/index' },
    { name: 'AspectRatio', path: '/pages/ui/aspect-ratio/index' },
    { name: 'Avatar', path: '/pages/ui/avatar/index' },
    { name: 'Badge', path: '/pages/ui/badge/index' },
    { name: 'Breadcrumb', path: '/pages/ui/breadcrumb/index' },
    { name: 'Button', path: '/pages/ui/button/index' },
    { name: 'Calendar', path: '/pages/ui/calendar/index' },
    { name: 'Card', path: '/pages/ui/card/index' },
    { name: 'Carousel', path: '/pages/ui/carousel/index' },
    { name: 'Checkbox', path: '/pages/ui/checkbox/index' },
    { name: 'Collapsible', path: '/pages/ui/collapsible/index' },
    { name: 'Command', path: '/pages/ui/command/index' },
    { name: 'ContextMenu', path: '/pages/ui/context-menu/index' },
    { name: 'Dialog', path: '/pages/ui/dialog/index' },
    { name: 'Drawer', path: '/pages/ui/drawer/index' },
    { name: 'DropdownMenu', path: '/pages/ui/dropdown-menu/index' },
    { name: 'Field', path: '/pages/ui/field/index' },
    { name: 'HoverCard', path: '/pages/ui/hover-card/index' },
    { name: 'Input', path: '/pages/ui/input/index' },
    { name: 'InputOTP', path: '/pages/ui/input-otp/index' },
    { name: 'Label', path: '/pages/ui/label/index' },
    { name: 'Menubar', path: '/pages/ui/menubar/index' },
    { name: 'NavigationMenu', path: '/pages/ui/navigation-menu/index' },
    { name: 'Pagination', path: '/pages/ui/pagination/index' },
    { name: 'Popover', path: '/pages/ui/popover/index' },
    { name: 'Progress', path: '/pages/ui/progress/index' },
    { name: 'RadioGroup', path: '/pages/ui/radio-group/index' },
    { name: 'Resizable', path: '/pages/ui/resizable/index' },
    { name: 'ScrollArea', path: '/pages/ui/scroll-area/index' },
    { name: 'Select', path: '/pages/ui/select/index' },
    { name: 'Separator', path: '/pages/ui/separator/index' },
    { name: 'Sheet', path: '/pages/ui/sheet/index' },
    { name: 'Skeleton', path: '/pages/ui/skeleton/index' },
    { name: 'Slider', path: '/pages/ui/slider/index' },
    { name: 'Sonner', path: '/pages/ui/sonner/index' },
    { name: 'Switch', path: '/pages/ui/switch/index' },
    { name: 'Table', path: '/pages/ui/table/index' },
    { name: 'Tabs', path: '/pages/ui/tabs/index' },
    { name: 'Textarea', path: '/pages/ui/textarea/index' },
    { name: 'Toast', path: '/pages/ui/toast/index' },
    { name: 'Toggle', path: '/pages/ui/toggle/index' },
    { name: 'ToggleGroup', path: '/pages/ui/toggle-group/index' },
    { name: 'Tooltip', path: '/pages/ui/tooltip/index' },
]
