export default defineAppConfig({
    pages: [
        'pages/index/index',
        'pages/ui/button/index',
        'pages/ui/card/index',
        'pages/ui/input/index',
        'pages/ui/tabs/index',
        'pages/ui/dialog/index',
        'pages/ui/avatar/index',
        'pages/ui/badge/index',
        'pages/ui/switch/index',
        'pages/ui/accordion/index',
        'pages/ui/alert/index',
        'pages/ui/alert-dialog/index',
        'pages/ui/aspect-ratio/index',
        'pages/ui/breadcrumb/index',
        'pages/ui/checkbox/index',
        'pages/ui/collapsible/index',
        'pages/ui/calendar/index',
        'pages/ui/command/index',
        'pages/ui/context-menu/index',
        'pages/ui/dropdown-menu/index',
        'pages/ui/drawer/index',
        'pages/ui/form/index',
        'pages/ui/hover-card/index',
        'pages/ui/input-otp/index',
        'pages/ui/label/index',
        'pages/ui/menubar/index',
        'pages/ui/navigation-menu/index',
        'pages/ui/pagination/index',
        'pages/ui/popover/index',
        'pages/ui/progress/index',
        'pages/ui/radio-group/index',
        'pages/ui/resizable/index',
        'pages/ui/scroll-area/index',
        'pages/ui/select/index',
        'pages/ui/separator/index',
        'pages/ui/sheet/index',
        'pages/ui/skeleton/index',
        'pages/ui/slider/index',
        'pages/ui/sonner/index',
        'pages/ui/table/index',
        'pages/ui/textarea/index',
        'pages/ui/toast/index',
        'pages/ui/toggle/index',
        'pages/ui/toggle-group/index',
        'pages/ui/tooltip/index',
        'pages/ui/carousel/index',
    ],
    window: {
        backgroundTextStyle: 'light',
        navigationBarBackgroundColor: '#fff',
        navigationBarTitleText: 'shadcn/ui',
        navigationBarTextStyle: 'black',
    },
})
